{ pkgs, lib, config, ... }:
{
  programs.neovim = {
    enable = true;
    defaultEditor = true;
    withNodeJs = true;
    withPython3 = true;
    withRuby = true;
    plugins = [
      pkgs.vimPlugins.nvim-treesitter.withAllGrammars
    ];
    initLua = ''require("main")'';
  };

  # Manually disable the autogenerated neovim config file
  # xdg.configFile."nvim/init.vim".enable = false;

  # Link the lua definitions from neovim so that I can use them when configuring it.
  home.file."neovim_lua" = {
    source = config.lib.file.mkOutOfStoreSymlink "${pkgs.neovim}/share/nvim/runtime/lua";
    target = ".local/share/nvim/runtime/lua";
    recursive = true;
  };
}
